
swagger: "2.0"
info:
  description: This is the swagger file that defines generated api
  version: "dev/0.0.1"
  title: API-qrest Generated
consumes:
  - application/json
produces:
  - application/json

definitions:
  qrest:
    type: object
    required:
      - id
    properties:
      id:
        type: string
        description: Id of the element
      createdAt:
        type: string
      updatedAt:
        type: string
      
      address:
        type: string

      age:
        type: number

      car:
        type: boolean

      hobbies:
        type: string

      name:
        type: string



#base path for server application
basePath: /api
# Paths supported by the server application
paths:
  /qrest:
    get:
      operationId: api.listAll
      tags:
        - qrest
      summary: Read the entire list of qrest
      description: Read the list of qrest
      responses:
        200:
          description: Successfully read qrest list operation
          schema:
            $ref: '#/definitions/qrest'
    post:
      operationId: api.createOne
      tags:
        - qrest
      summary: Create a qrest and add it to the qrest list
      description: Create a new qrest in the qrest list
      parameters:
        - name: object
          in: body
          description: qrest to create
          required: True
          schema:
            $ref: '#/definitions/qrest'
      responses:
        201:
          description: Successfully created qrest in list

  /qrest/{id}:
    get:
      operationId: api.getOne
      tags:
        - qrest
      summary: Read one qrest from the qrest list
      description: Read one qrest from the qrest list
      parameters:
        - name: id
          in: path
          description: Unique model identifier for qrest
          type: string
          required: True
      responses:
        200:
          description: Successfully read person from people list operation
          schema:
            $ref: '#/definitions/qrest'
    put:
      operationId: api.updateOne
      tags:
        - qrest
      summary: Update a qrest in qrest
      description: Update a qrest in qrest
      parameters:
        - name: id
          in: path
          description: Unique model identifier for qrest
          type: string
          required: True
        - name: object
          in: body
          schema:
            $ref: '#/definitions/qrest'
      responses:
        200:
          description: Successfully updated qrest
    delete:
      operationId: api.deleteOne
      tags:
        - qrest
      summary: Delete a qrest from the qrest list
      description: Delete a person
      parameters:
        - name: id
          in: path
          type: string
          required: True
          description: Unique model identifier for qrest
      responses:
        200:
          description: Successfully deleted a qrest
